[package]
name = "next-rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "time"] }
serde_json = { version = "1", features = ["raw_value"] }
serde = { version = "1", features = ["derive"] }
vercel_runtime = { version = "1" }
url = "2"
regex = "1"
rand = "0.8"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1"] }
postgres-native-tls = "0.5"
native-tls = "0.2"
openssl = { version = "0.10", features = ["vendored"] }

[[bin]]
name = "hello"
path = "api/hello.rs"

[[bin]]
name = "esp32_rust"
path = "api/esp32_rust.rs"

[[bin]]
name = "esp32_sensor"
path = "api/esp32_sensor.rs"

[[bin]]
name = "send_sensor_data"
path = "api/send_sensor_data.rs"

[[bin]]
name = "cars"
path = "api/cars.rs"

[[bin]]
name = "cars_id"
path = "api/cars/[id].rs"

[[bin]]
name = "test_db_connection"
path = "test_db_connection.rs"